  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
  add_header Cache-Control "no-store, max-age=0";
  add_header Content-Security-Policy "default-src 'self' $PORTAL_BE_API https://login.microsoftonline.com https://*.microsoftonline.com https://*.azure.com data:; form-action 'self' $PORTAL_BE_API; object-src 'self' $PORTAL_BE_API; frame-ancestors 'self' $PORTAL_BE_API; frame-src 'self' $PORTAL_BE_API $CHAT_FE_URL $NOTES_FE_URL https://login.microsoftonline.com; upgrade-insecure-requests; block-all-mixed-content; style-src 'self' 'unsafe-inline' $PORTAL_BE_API; font-src 'self' $PORTAL_BE_API data:; img-src 'self' data: $PORTAL_BE_API https://flagcdn.com; script-src 'self' data: https://*.microsoftonline.com
  add_header Cross-Origin-Embedder-Policy "unsafe-none";
  add_header Cross-Origin-Opener-Policy "same-site";
  add_header Cross-Origin-Resource-Policy "same-site";
  add_header Permissions-Policy 'accelerometer=(),autoplay=(),camera=(),display-capture=(),encrypted-media=(),fullscreen=(),gamepad=(),geolocation=(),gyroscope=(),magnetometer=(),microphone=(self "$CHAT_FE_URL " "$NOTES_FE_URL"),midi=(),payment=(),picture-in-picture=(),publickey-credentials-get=(),sync-xhr=(self),usb=(),screen-wake-lock=(),web-share=(),xr-spatial-tracking=()';
  add_header Pragma "no-cache";
  add_header Referrer-Policy "no-referrer";
  add_header X-Content-Type-Options "nosniff";
  add_header X-Permitted-Cross-Domain-Policies "none";
  $CHAT_FE_URL $NOTES_FE_URL 
  $PORTAL_FE_URL
